
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer, Zoom,Slide } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInForceRedirectUrl="/dashboard"
      signUpForceRedirectUrl="/dashboard"
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          {children}


<ToastContainer
  position="bottom-right"
  autoClose={3000}
  newestOnTop
  closeOnClick
  pauseOnHover
  draggable
  transition={Slide}
  toastClassName="group relative flex items-center gap-3 p-4 rounded-xl overflow-hidden bg-[#0A0A0A]/85 backdrop-blur-xl border border-white/10 shadow-[0_10px_40px_rgba(0,0,0,0.7)]"
  progressClassName="bg-gradient-to-r from-[#D31100] via-red-500 to-[#ff3b2f]"
/>
        </body>
      </html>
    </ClerkProvider>
  );
}
